services:
  app1:
    build: .
    hostname: "node1.dev"
    environment:
      - RELEASE_NODE=app@node1.dev
      - RELEASE_DISTRIBUTION=name
    ports:
      - "127.0.0.1:4001:4000"
  app2:
    build: .
    hostname: "n2.dev"
    environment:
      - RELEASE_NODE=app@node2.dev
      - RELEASE_DISTRIBUTION=name
    ports:
      - "127.0.0.1:4002:4000"
  app3:
    build: .
    hostname: "n3.dev"
    environment:
      - RELEASE_NODE=app@node3.dev
      - RELEASE_DISTRIBUTION=name
    ports:
      - "127.0.0.1:4003:4000"
networks:
  default:
    external: true
    name: cluster-net